server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili?autoReconnect=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver